/*
 * This source file was generated by the Gradle 'init' task
 */

// ******************
// Last names: Campo, Hallare, Lobo, Rebollos
// Language: Kotlin
// Paradigm(s): Object-Oriented Programming, Functional Programming
// ******************
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val accounts = mutableMapOf<String, Double>()
    val interestRate = 0.05
    val currencyNames = arrayOf("PHP", "USD", "JPY", "GBP", "EUR", "CNY")
    val exchangeRates = DoubleArray(6) { 1.0 }

    exchangeRates[0] = 1.0
    exchangeRates[1] = 52.0
    exchangeRates[2] = 0.37
    exchangeRates[3] = 68.0
    exchangeRates[4] = 60.0
    exchangeRates[5] = 7.0

    println("Welcome to the Banking and Currency App!")

    while (true) {
        println("\n=== MAIN MENU ===")
        println("[1] Register Account Name")
        println("[2] Deposit Amount")
        println("[3] Withdraw Amount")
        println("[4] Currency Exchange")
        println("[5] Record Exchange Rates")
        println("[6] Show Interest Amount")
        println("[0] Exit")
        print("Select Transaction: ")

        val choice = readIntInput()

        when (choice) {
            0 -> {
                println("\nThank you for using the Banking and Currency App!")
                return
            }
            in 1..6 -> {
                do {
                    when (choice) {
                        1 -> registerAccount(accounts)
                        2 -> deposit(accounts)
                        3 -> withdraw(accounts)
                        4 -> currencyExchange(exchangeRates, currencyNames)
                        5 -> recordRates(exchangeRates, currencyNames)
                        6 -> showInterest(accounts, interestRate)
                    }
                } while (!askReturnToMenu())
            }
            else -> println("Invalid choice. Please select a number between 0 and 6.")
        }
    }
}

// ---------- Utility Input Functions ----------

fun readIntInput(): Int {
    val input = readLine()
    return try {
        input?.toInt() ?: -1
    } catch (e: Exception) {
        -1
    }
}

fun readDoubleInput(): Double {
    val input = readLine()
    return try {
        input?.toDouble() ?: 0.0
    } catch (e: Exception) {
        println("Invalid number, defaulting to 0.")
        0.0
    }
}

fun promptAccountName(): String {
    print("Account Name: ")
    return readLine()?.trim().orEmpty()
}

fun findAccountKey(accounts: Map<String, Double>, name: String): String? {
    return accounts.keys.firstOrNull { it.equals(name, ignoreCase = true) }
}

fun askReturnToMenu(): Boolean {
    while (true) {
        print("\nBack to Main Menu (Y/N): ")
        val response = readLine()?.trim()?.uppercase()
        if (response == "Y") {
            return true
        }
        if (response == "N") {
            return false
        }
        println("Invalid input. Please enter only 'Y' or 'N'.")
    }
}

// ---------- Main Features ----------

fun registerAccount(accounts: MutableMap<String, Double>) {
    print("Enter Account Name: ")
    val name = readLine()?.trim().orEmpty()
    if (name.isEmpty()) {
        println("Account name cannot be empty.")
        return
    }
    if (findAccountKey(accounts, name) != null) {
        println("Account already exists: $name")
        return
    }
    accounts[name] = 0.0
    println("Account Registered: $name")
}

fun deposit(accounts: MutableMap<String, Double>) {
    val name = promptAccountName()
    if (name.isEmpty()) {
        println("Account name cannot be empty.")
        return
    }
    val key = findAccountKey(accounts, name)
    if (key == null) {
        println("Account not found. Please register first.")
        return
    }
    val currentBalance = accounts.getValue(key)
    println("Account Name: $key")
    println("Current Balance: ${"%.2f".format(currentBalance)} PHP")
    print("Enter Deposit Amount: ")
    val depositAmount = readDoubleInput()
    if (depositAmount <= 0) {
        println("Invalid deposit amount.")
        return
    }
    val newBalance = currentBalance + depositAmount
    accounts[key] = newBalance
    println("Updated Balance: ${"%.2f".format(newBalance)} PHP")
}

fun withdraw(accounts: MutableMap<String, Double>) {
    val name = promptAccountName()
    if (name.isEmpty()) {
        println("Account name cannot be empty.")
        return
    }
    val key = findAccountKey(accounts, name)
    if (key == null) {
        println("Account not found. Please register first.")
        return
    }
    val currentBalance = accounts.getValue(key)
    println("Account Name: $key")
    println("Current Balance: ${"%.2f".format(currentBalance)} PHP")
    print("Enter Withdraw Amount: ")
    val withdrawAmount = readDoubleInput()

    if (withdrawAmount <= 0) {
        println("Invalid withdrawal amount.")
        return
    }
    if (withdrawAmount > currentBalance) {
        println("Insufficient funds.")
        return
    }

    val newBalance = currentBalance - withdrawAmount
    accounts[key] = newBalance
    println("Updated Balance: ${"%.2f".format(newBalance)} PHP")
}

fun recordRates(rates: DoubleArray, names: Array<String>) {
    println("\nRecord Exchange Rates")
    for (i in 1 until names.size) {
        println("[${i}] ${names[i]}")
    }
    print("Select Currency to Update: ")
    val choice = readIntInput()

    if (choice in 1..5) {
        print("Enter New Rate for ${names[choice]}: ")
        val newRate = readDoubleInput()
        if (newRate > 0) {
            rates[choice] = newRate
            println("Updated ${names[choice]} Rate: ${rates[choice]}")
        } else {
            println("Invalid rate. Must be greater than 0.")
        }
    } else {
        println("Invalid selection.")
    }
}

fun currencyExchange(rates: DoubleArray, names: Array<String>) {
    println("\nForeign Currency Exchange")
    println("Source Currency Options:")
    for (i in names.indices) {
        println("[${i + 1}] ${names[i]}")
    }
    print("Source Currency: ")
    val source = readIntInput() - 1

    if (source !in 0..5) {
        println("Invalid source currency.")
        return
    }

    print("Source Amount: ")
    val amount = readDoubleInput()
    if (amount <= 0) {
        println("Amount must be greater than 0.")
        return
    }

    println("Convert To:")
    for (i in names.indices) {
        println("[${i + 1}] ${names[i]}")
    }
    print("Target Currency: ")
    val target = readIntInput() - 1

    if (target !in 0..5) {
        println("Invalid target currency.")
        return
    }

    val phpValue = amount * rates[source]
    val converted = phpValue / rates[target]
    println("Exchange Amount: ${"%.2f".format(converted)} ${names[target]}")
}

fun showInterest(accounts: Map<String, Double>, rate: Double) {
    val name = promptAccountName()
    if (name.isEmpty()) {
        println("Account name cannot be empty.")
        return
    }
    val key = findAccountKey(accounts, name)
    if (key == null) {
        println("Account not found. Please register first.")
        return
    }
    val balance = accounts.getValue(key)
    println("\nShow Interest Amount")
    println("Account Name: $key")
    println("Current Balance: ${"%.2f".format(balance)} PHP")
    println("Interest Rate: 5% per annum")
    print("Enter Number of Days: ")
    val days = readIntInput()

    if (days <= 0) {
        println("Invalid number of days.")
        return
    }

    var currentBalance = balance
    println("Day | Interest | Balance")
    for (d in 1..days) {
        val interest = currentBalance * (rate / 365)
        currentBalance += interest
        println("$d | ${"%.2f".format(interest)} | ${"%.2f".format(currentBalance)}")
    }
}
